spring:
  jpa:
    database-platform: H2
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments : true
        jdbc:
          batch_size: 2000
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    master:
      platform: h2
      jdbc-url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=true
      username: sa
      password:
      driver-class-name: org.h2.Driver
    slave:
      platform: h2
      jdbc-url: jdbc:h2:tcp://localhost/~/test;AUTO_SERVER=true
      username: sa
      password:
      driver-class-name: org.h2.Driver